var nameIconMap = map[string]IconProperties{
	"._sc_":                                {Icon: "\ue65f", Color: 71},   // 
	".astylerc":                            {Icon: "\uf0068", Color: 203}, // 󰁨
	".autorc":                              {Icon: "\uf0f86", Color: 203}, // 󰾆
	".babel-plugin-macrosrc":               {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.cjs":           {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.cts":           {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.js":            {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.json":          {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.json5":         {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.jsonc":         {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.mjs":           {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.mts":           {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.toml":          {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.ts":            {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.yaml":          {Icon: "\ue639", Color: 221},  // 
	".babel-plugin-macrosrc.yml":           {Icon: "\ue639", Color: 221},  // 
	".babelrc.cjs":                         {Icon: "\ue639", Color: 221},  // 
	".babelrc.cts":                         {Icon: "\ue639", Color: 221},  // 
	".babelrc.js":                          {Icon: "\ue639", Color: 221},  // 
	".babelrc.json":                        {Icon: "\ue639", Color: 221},  // 
	".babelrc.json5":                       {Icon: "\ue639", Color: 221},  // 
	".babelrc.jsonc":                       {Icon: "\ue639", Color: 221},  // 
	".babelrc.mjs":                         {Icon: "\ue639", Color: 221},  // 
	".babelrc.mts":                         {Icon: "\ue639", Color: 221},  // 
	".babelrc.toml":                        {Icon: "\ue639", Color: 221},  // 
	".babelrc.ts":                          {Icon: "\ue639", Color: 221},  // 
	".babelrc.yaml":                        {Icon: "\ue639", Color: 221},  // 
	".babelrc.yml":                         {Icon: "\ue639", Color: 221},  // 
	".bazelignore":                         {Icon: "\ue63a", Color: 71},   // 
	".bazelrc":                             {Icon: "\ue63a", Color: 71},   // 
	".bazelversion":                        {Icon: "\ue63a", Color: 71},   // 
	".bowerrc":                             {Icon: "\ue61a", Color: 203},  // 
	".buildignore":                         {Icon: "\uf013", Color: 75},   // 
	".clang-format":                        {Icon: "\uf013", Color: 75},   // 
	".clang-tidy":                          {Icon: "\uf013", Color: 75},   // 
	".coffeelintignore":                    {Icon: "\ue61b", Color: 65},   // 
	".commitlint.yaml":                     {Icon: "\ueafc", Color: 30},   // 
	".commitlint.yml":                      {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc":                        {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.cjs":                    {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.cts":                    {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.js":                     {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.json":                   {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.json5":                  {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.jsonc":                  {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.mjs":                    {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.mts":                    {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.toml":                   {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.ts":                     {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.yaml":                   {Icon: "\ueafc", Color: 30},   // 
	".commitlintrc.yml":                    {Icon: "\ueafc", Color: 30},   // 
	".coveralls.yml":                       {Icon: "\ueb59", Color: 131},  // 
	".ember-cli":                           {Icon: "\uf0b30", Color: 202}, // 󰬰
	".ember-cli.js":                        {Icon: "\uf0b30", Color: 202}, // 󰬰
	".env.alpha":                           {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.defaults":                        {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.dev":                             {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.development":                     {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.development.local":               {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.dist":                            {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.e2e":                             {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.example":                         {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.local":                           {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.preview":                         {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.prod":                            {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.production":                      {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.production.local":                {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.qa":                              {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.qa.local":                        {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.sample":                          {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.schema":                          {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.stage":                           {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.staging":                         {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.staging.local":                   {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.template":                        {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.test":                            {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.test.local":                      {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.testing":                         {Icon: "\uf066a", Color: 214}, // 󰙪
	".env.uat":                             {Icon: "\uf066a", Color: 214}, // 󰙪
	".esformatter":                         {Icon: "\ue60b", Color: 214},  // 
	".eslintcache":                         {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc-jsdoc.js":                   {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc-md.js":                      {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.base.json":                  {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.cjs":                        {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.cts":                        {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.js":                         {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.json":                       {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.json5":                      {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.jsonc":                      {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.mjs":                        {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.mts":                        {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.toml":                       {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.ts":                         {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.yaml":                       {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".eslintrc.yml":                        {Icon: "\uf0c7a", Color: 61},  // 󰱺
	".esmrc":                               {Icon: "\ued0d", Color: 71},   // 
	".firebaserc":                          {Icon: "\uf0967", Color: 214}, // 󰥧
	".gcloudignore":                        {Icon: "\uf11f6", Color: 69},  // 󱇶
	".gdignore":                            {Icon: "\ue65f", Color: 71},   // 
	".git-blame-ignore":                    {Icon: "\uf02a2", Color: 166}, // 󰊢
	".git-for-windows-updater":             {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitattributes-global":                {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitattributes_global":                {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitignore-global":                    {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitignore_global":                    {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitinclude":                          {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitkeep":                             {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitmessage":                          {Icon: "\uf02a2", Color: 166}, // 󰊢
	".gitpreserve":                         {Icon: "\uf02a2", Color: 166}, // 󰊢
	".graphqlconfig":                       {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc":                           {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.cjs":                       {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.cts":                       {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.js":                        {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.json":                      {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.json5":                     {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.jsonc":                     {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.mjs":                       {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.mts":                       {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.toml":                      {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.ts":                        {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.yaml":                      {Icon: "\uf0877", Color: 204}, // 󰡷
	".graphqlrc.yml":                       {Icon: "\uf0877", Color: 204}, // 󰡷
	".hhconfig":                            {Icon: "\ue663", Color: 255},  // 
	".huskyrc":                             {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.cjs":                         {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.cts":                         {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.js":                          {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.json":                        {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.json5":                       {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.jsonc":                       {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.mjs":                         {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.mts":                         {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.toml":                        {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.ts":                          {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.yaml":                        {Icon: "\uf03e9", Color: 109}, // 󰏩
	".huskyrc.yml":                         {Icon: "\uf03e9", Color: 109}, // 󰏩
	".io-config.json":                      {Icon: "\ue66b", Color: 69},   // 
	".istanbul.yml":                        {Icon: "\uf1827", Color: 221}, // 󱠧
	".jsbeautifyrc":                        {Icon: "\ue60b", Color: 214},  // 
	".jscsrc":                              {Icon: "\ue60b", Color: 214},  // 
	".jshintignore":                        {Icon: "\uf013", Color: 75},   // 
	".jshintrc":                            {Icon: "\ue60b", Color: 214},  // 
	".k8s.yaml":                            {Icon: "\uf10fe", Color: 69},  // 󱃾
	".k8s.yml":                             {Icon: "\uf10fe", Color: 69},  // 󱃾
	".keep":                                {Icon: "\uf02a2", Color: 166}, // 󰊢
	".knip.json":                           {Icon: "\uf0c4", Color: 202},  // 
	".knip.jsonc":                          {Icon: "\uf0c4", Color: 202},  // 
	".lighthouserc.cjs":                    {Icon: "\uf09ff", Color: 202}, // 󰧿
	".lighthouserc.js":                     {Icon: "\uf09ff", Color: 202}, // 󰧿
	".lighthouserc.json":                   {Icon: "\uf09ff", Color: 202}, // 󰧿
	".lighthouserc.yaml":                   {Icon: "\uf09ff", Color: 202}, // 󰧿
	".lighthouserc.yml":                    {Icon: "\uf09ff", Color: 202}, // 󰧿
	".lintstagedrc":                        {Icon: "\ue60b", Color: 214},  // 
	".luacheckrc":                          {Icon: "\ue620", Color: 75},   // 
	".mcattributes":                        {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcdefinitions":                       {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcignore":                            {Icon: "\uf0373", Color: 71},  // 󰍳
	".mincloudrc":                          {Icon: "\uf0c2", Color: 32},   // 
	".mocharc.js":                          {Icon: "\ue61b", Color: 138},  // 
	".mocharc.json":                        {Icon: "\ue61b", Color: 138},  // 
	".mocharc.jsonc":                       {Icon: "\ue61b", Color: 138},  // 
	".mocharc.yaml":                        {Icon: "\ue61b", Color: 138},  // 
	".mocharc.yml":                         {Icon: "\ue61b", Color: 138},  // 
	".modernizrrc":                         {Icon: "\ue720", Color: 161},  // 
	".modernizrrc.js":                      {Icon: "\ue720", Color: 161},  // 
	".modernizrrc.json":                    {Icon: "\ue720", Color: 161},  // 
	".mrconfig":                            {Icon: "\uf013", Color: 75},   // 
	".node-version":                        {Icon: "\ued0d", Color: 71},   // 
	".nowignore":                           {Icon: "\uf0536", Color: 188}, // 󰔶
	".nuxtignore":                          {Icon: "\uf1106", Color: 42},  // 󱄆
	".nycrc":                               {Icon: "\uf1827", Color: 221}, // 󱠧
	".nycrc.json":                          {Icon: "\uf1827", Color: 221}, // 󱠧
	".nycrc.yaml":                          {Icon: "\uf1827", Color: 221}, // 󱠧
	".nycrc.yml":                           {Icon: "\uf1827", Color: 221}, // 󱠧
	".parcelrc":                            {Icon: "\ued95", Color: 215},  // 
	".php-cs-fixer.dist.php":               {Icon: "\uf031f", Color: 203}, // 󰌟
	".php-cs-fixer.php":                    {Icon: "\uf031f", Color: 203}, // 󰌟
	".php_cs":                              {Icon: "\uf031f", Color: 203}, // 󰌟
	".php_cs.dist":                         {Icon: "\uf031f", Color: 203}, // 󰌟
	".php_cs.dist.php":                     {Icon: "\uf031f", Color: 203}, // 󰌟
	".php_cs.php":                          {Icon: "\uf031f", Color: 203}, // 󰌟
	".prettierrc.cjs":                      {Icon: "\ue6b4", Color: 167},  // 
	".prettierrc.cts":                      {Icon: "\ue6b4", Color: 167},  // 
	".prettierrc.js":                       {Icon: "\ue6b4", Color: 167},  // 
	".prettierrc.jsonc":                    {Icon: "\ue6b4", Color: 167},  // 
	".prettierrc.mjs":                      {Icon: "\ue6b4", Color: 167},  // 
	".prettierrc.mts":                      {Icon: "\ue6b4", Color: 167},  // 
	".prettierrc.ts":                       {Icon: "\ue6b4", Color: 167},  // 
	".pug-lintrc":                          {Icon: "\ue686", Color: 223},  // 
	".pug-lintrc.js":                       {Icon: "\ue686", Color: 223},  // 
	".pug-lintrc.json":                     {Icon: "\ue686", Color: 223},  // 
	".renovaterc":                          {Icon: "\uee72", Color: 214},  // 
	".renovaterc.json":                     {Icon: "\uee72", Color: 214},  // 
	".Rhistory":                            {Icon: "\ue68a", Color: 32},   // 
	".slugignore":                          {Icon: "\uf1677", Color: 214}, // 󱙷
	".stryker.conf.cjs":                    {Icon: "\uf01a3", Color: 203}, // 󰆣
	".stryker.conf.js":                     {Icon: "\uf01a3", Color: 203}, // 󰆣
	".stryker.conf.json":                   {Icon: "\uf01a3", Color: 203}, // 󰆣
	".stryker.conf.mjs":                    {Icon: "\uf01a3", Color: 203}, // 󰆣
	".stylelintcache":                      {Icon: "\ue695", Color: 188},  // 
	".stylelintignore":                     {Icon: "\ue695", Color: 188},  // 
	".stylelintrc":                         {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.cjs":                     {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.cts":                     {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.js":                      {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.json":                    {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.json5":                   {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.jsonc":                   {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.mjs":                     {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.mts":                     {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.toml":                    {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.ts":                      {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.yaml":                    {Icon: "\ue695", Color: 188},  // 
	".stylelintrc.yml":                     {Icon: "\ue695", Color: 188},  // 
	".svgrrc":                              {Icon: "\ued46", Color: 208},  // 
	".svgrrc.cjs":                          {Icon: "\ued46", Color: 208},  // 
	".svgrrc.cts":                          {Icon: "\ued46", Color: 208},  // 
	".svgrrc.js":                           {Icon: "\ued46", Color: 208},  // 
	".svgrrc.json":                         {Icon: "\ued46", Color: 208},  // 
	".svgrrc.json5":                        {Icon: "\ued46", Color: 208},  // 
	".svgrrc.jsonc":                        {Icon: "\ued46", Color: 208},  // 
	".svgrrc.mjs":                          {Icon: "\ued46", Color: 208},  // 
	".svgrrc.mts":                          {Icon: "\ued46", Color: 208},  // 
	".svgrrc.toml":                         {Icon: "\ued46", Color: 208},  // 
	".svgrrc.ts":                           {Icon: "\ued46", Color: 208},  // 
	".svgrrc.yaml":                         {Icon: "\ued46", Color: 208},  // 
	".svgrrc.yml":                          {Icon: "\ued46", Color: 208},  // 
	".syncpackrc":                          {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.cjs":                      {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.cts":                      {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.js":                       {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.json":                     {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.json5":                    {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.jsonc":                    {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.mjs":                      {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.mts":                      {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.toml":                     {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.ts":                       {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.yaml":                     {Icon: "\uf46a", Color: 113},  // 
	".syncpackrc.yml":                      {Icon: "\uf46a", Color: 113},  // 
	".travis.yml":                          {Icon: "\ue77e", Color: 107},  // 
	".vercelignore":                        {Icon: "\uf0536", Color: 188}, // 󰔶
	".whitesource":                         {Icon: "\ue60b", Color: 214},  // 
	".yardopts":                            {Icon: "\uf013", Color: 75},   // 
	".yarn-integrity":                      {Icon: "\ue6a7", Color: 32},   // 
	".yarnclean":                           {Icon: "\ue6a7", Color: 32},   // 
	".yarnrc":                              {Icon: "\ue6a7", Color: 32},   // 
	".yarnrc.yaml":                         {Icon: "\ue6a7", Color: 32},   // 
	".yarnrc.yml":                          {Icon: "\ue6a7", Color: 32},   // 
	"OWNERS":                               {Icon: "\uf0008", Color: 142}, // 󰀈
	"PklProject":                           {Icon: "\uf013", Color: 71},   // 
	"PklProject.deps.json":                 {Icon: "\uf013", Color: 71},   // 
	"_sc_":                                 {Icon: "\ue65f", Color: 71},   // 
	"apacheconf":                           {Icon: "\ue7c4", Color: 125},  // 
	"architecture":                         {Icon: "\uf0358", Color: 71},  // 󰍘
	"architecture.md":                      {Icon: "\uf0358", Color: 71},  // 󰍘
	"architecture.rst":                     {Icon: "\uf0358", Color: 71},  // 󰍘
	"architecture.txt":                     {Icon: "\uf0358", Color: 71},  // 󰍘
	"artisan":                              {Icon: "\uf2f7", Color: 203},  // 
	"astro.config.cjs":                     {Icon: "\ue6b3", Color: 202},  // 
	"astro.config.cts":                     {Icon: "\ue6b3", Color: 202},  // 
	"astro.config.js":                      {Icon: "\ue6b3", Color: 202},  // 
	"astro.config.mjs":                     {Icon: "\ue6b3", Color: 202},  // 
	"astro.config.mts":                     {Icon: "\ue6b3", Color: 202},  // 
	"astro.config.ts":                      {Icon: "\ue6b3", Color: 202},  // 
	"authors":                              {Icon: "\uf4fd", Color: 203},  // 
	"authors.md":                           {Icon: "\uf4fd", Color: 203},  // 
	"authors.rst":                          {Icon: "\uf4fd", Color: 203},  // 
	"authors.txt":                          {Icon: "\uf4fd", Color: 203},  // 
	"auto-config.js":                       {Icon: "\uf0f86", Color: 203}, // 󰾆
	"auto-config.json":                     {Icon: "\uf0f86", Color: 203}, // 󰾆
	"auto-config.ts":                       {Icon: "\uf0f86", Color: 203}, // 󰾆
	"auto-config.yaml":                     {Icon: "\uf0f86", Color: 203}, // 󰾆
	"auto-config.yml":                      {Icon: "\uf0f86", Color: 203}, // 󰾆
	"auto.config.js":                       {Icon: "\uf0f86", Color: 203}, // 󰾆
	"auto.config.ts":                       {Icon: "\uf0f86", Color: 203}, // 󰾆
	"azure-pipelines-main.yaml":            {Icon: "\uf14de", Color: 32},  // 󱓞
	"azure-pipelines-main.yml":             {Icon: "\uf14de", Color: 32},  // 󱓞
	"azure-pipelines.yaml":                 {Icon: "\uf14de", Color: 32},  // 󱓞
	"azure-pipelines.yml":                  {Icon: "\uf14de", Color: 32},  // 󱓞
	"babel-plugin-macros.config.cjs":       {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.cts":       {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.js":        {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.json":      {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.json5":     {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.jsonc":     {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.mjs":       {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.mts":       {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.toml":      {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.ts":        {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.yaml":      {Icon: "\ue639", Color: 221},  // 
	"babel-plugin-macros.config.yml":       {Icon: "\ue639", Color: 221},  // 
	"babel-transform.js":                   {Icon: "\ue639", Color: 221},  // 
	"babel.config.cjs":                     {Icon: "\ue639", Color: 221},  // 
	"babel.config.cts":                     {Icon: "\ue639", Color: 221},  // 
	"babel.config.js":                      {Icon: "\ue639", Color: 221},  // 
	"babel.config.json":                    {Icon: "\ue639", Color: 221},  // 
	"babel.config.json5":                   {Icon: "\ue639", Color: 221},  // 
	"babel.config.jsonc":                   {Icon: "\ue639", Color: 221},  // 
	"babel.config.mjs":                     {Icon: "\ue639", Color: 221},  // 
	"babel.config.mts":                     {Icon: "\ue639", Color: 221},  // 
	"babel.config.toml":                    {Icon: "\ue639", Color: 221},  // 
	"babel.config.ts":                      {Icon: "\ue639", Color: 221},  // 
	"babel.config.yaml":                    {Icon: "\ue639", Color: 221},  // 
	"babel.config.yml":                     {Icon: "\ue639", Color: 221},  // 
	"bitbucket-pipelines.yaml":             {Icon: "\uf171", Color: 32},   // 
	"bitbucket-pipelines.yml":              {Icon: "\uf171", Color: 32},   // 
	"bower.json":                           {Icon: "\ue61a", Color: 203},  // 
	"cargo.toml":                           {Icon: "\uf1b3", Color: 216},  // 
	"cdp.pid":                              {Icon: "\ue60b", Color: 214},  // 
	"changelog":                            {Icon: "\uf1038", Color: 113}, // 󱀸
	"changelog.md":                         {Icon: "\uf1038", Color: 113}, // 󱀸
	"changelog.rst":                        {Icon: "\uf1038", Color: 113}, // 󱀸
	"changelog.txt":                        {Icon: "\uf1038", Color: 113}, // 󱀸
	"changes":                              {Icon: "\uf1038", Color: 113}, // 󱀸
	"changes.md":                           {Icon: "\uf1038", Color: 113}, // 󱀸
	"changes.rst":                          {Icon: "\uf1038", Color: 113}, // 󱀸
	"changes.txt":                          {Icon: "\uf1038", Color: 113}, // 󱀸
	"code_of_conduct":                      {Icon: "\uf014e", Color: 185}, // 󰅎
	"code_of_conduct.md":                   {Icon: "\uf014e", Color: 185}, // 󰅎
	"code_of_conduct.txt":                  {Icon: "\uf014e", Color: 185}, // 󰅎
	"codeowners":                           {Icon: "\uf0008", Color: 142}, // 󰀈
	"coffeelint.json":                      {Icon: "\ue61b", Color: 65},   // 
	"commitlint.config.cjs":                {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.cts":                {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.json":               {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.json5":              {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.jsonc":              {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.mjs":                {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.mts":                {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.toml":               {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.yaml":               {Icon: "\ueafc", Color: 30},   // 
	"commitlint.config.yml":                {Icon: "\ueafc", Color: 30},   // 
	"compose.alpha.yaml":                   {Icon: "\uf21f", Color: 32},   // 
	"compose.alpha.yml":                    {Icon: "\uf21f", Color: 32},   // 
	"compose.beta.yaml":                    {Icon: "\uf21f", Color: 32},   // 
	"compose.beta.yml":                     {Icon: "\uf21f", Color: 32},   // 
	"compose.ci.yaml":                      {Icon: "\uf21f", Color: 32},   // 
	"compose.ci.yml":                       {Icon: "\uf21f", Color: 32},   // 
	"compose.dev.yaml":                     {Icon: "\uf21f", Color: 32},   // 
	"compose.dev.yml":                      {Icon: "\uf21f", Color: 32},   // 
	"compose.development.yaml":             {Icon: "\uf21f", Color: 32},   // 
	"compose.development.yml":              {Icon: "\uf21f", Color: 32},   // 
	"compose.local.yaml":                   {Icon: "\uf21f", Color: 32},   // 
	"compose.local.yml":                    {Icon: "\uf21f", Color: 32},   // 
	"compose.override.yaml":                {Icon: "\uf21f", Color: 32},   // 
	"compose.override.yml":                 {Icon: "\uf21f", Color: 32},   // 
	"compose.prod.yaml":                    {Icon: "\uf21f", Color: 32},   // 
	"compose.prod.yml":                     {Icon: "\uf21f", Color: 32},   // 
	"compose.production.yaml":              {Icon: "\uf21f", Color: 32},   // 
	"compose.production.yml":               {Icon: "\uf21f", Color: 32},   // 
	"compose.stage.yaml":                   {Icon: "\uf21f", Color: 32},   // 
	"compose.stage.yml":                    {Icon: "\uf21f", Color: 32},   // 
	"compose.staging.yaml":                 {Icon: "\uf21f", Color: 32},   // 
	"compose.staging.yml":                  {Icon: "\uf21f", Color: 32},   // 
	"compose.test.yaml":                    {Icon: "\uf21f", Color: 32},   // 
	"compose.test.yml":                     {Icon: "\uf21f", Color: 32},   // 
	"compose.testing.yaml":                 {Icon: "\uf21f", Color: 32},   // 
	"compose.testing.yml":                  {Icon: "\uf21f", Color: 32},   // 
	"compose.web.yaml":                     {Icon: "\uf21f", Color: 32},   // 
	"compose.web.yml":                      {Icon: "\uf21f", Color: 32},   // 
	"compose.worker.yaml":                  {Icon: "\uf21f", Color: 32},   // 
	"compose.worker.yml":                   {Icon: "\uf21f", Color: 32},   // 
	"composer.lock":                        {Icon: "\ue60b", Color: 214},  // 
	"confluence":                           {Icon: "\uef3f", Color: 33},   // 
	"containerfile.alpha":                  {Icon: "\uf21f", Color: 32},   // 
	"containerfile.beta":                   {Icon: "\uf21f", Color: 32},   // 
	"containerfile.ci":                     {Icon: "\uf21f", Color: 32},   // 
	"containerfile.dev":                    {Icon: "\uf21f", Color: 32},   // 
	"containerfile.development":            {Icon: "\uf21f", Color: 32},   // 
	"containerfile.local":                  {Icon: "\uf21f", Color: 32},   // 
	"containerfile.prod":                   {Icon: "\uf21f", Color: 32},   // 
	"containerfile.production":             {Icon: "\uf21f", Color: 32},   // 
	"containerfile.stage":                  {Icon: "\uf21f", Color: 32},   // 
	"containerfile.staging":                {Icon: "\uf21f", Color: 32},   // 
	"containerfile.test":                   {Icon: "\uf21f", Color: 32},   // 
	"containerfile.testing":                {Icon: "\uf21f", Color: 32},   // 
	"containerfile.web":                    {Icon: "\uf21f", Color: 32},   // 
	"containerfile.worker":                 {Icon: "\uf21f", Color: 32},   // 
	"contributing":                         {Icon: "\uf014d", Color: 220}, // 󰅍
	"contributing.md":                      {Icon: "\uf014d", Color: 220}, // 󰅍
	"contributing.rst":                     {Icon: "\uf014d", Color: 220}, // 󰅍
	"contributing.txt":                     {Icon: "\uf014d", Color: 220}, // 󰅍
	"contributors":                         {Icon: "\uf4fd", Color: 106},  // 
	"contributors.md":                      {Icon: "\uf4fd", Color: 106},  // 
	"contributors.rst":                     {Icon: "\uf4fd", Color: 106},  // 
	"contributors.txt":                     {Icon: "\uf4fd", Color: 106},  // 
	"copying.md":                           {Icon: "\uf0124", Color: 202}, // 󰄤
	"copying.rst":                          {Icon: "\uf0124", Color: 202}, // 󰄤
	"copying.txt":                          {Icon: "\uf0124", Color: 202}, // 󰄤
	"copyright":                            {Icon: "\uf0124", Color: 202}, // 󰄤
	"copyright.md":                         {Icon: "\uf0124", Color: 202}, // 󰄤
	"copyright.rst":                        {Icon: "\uf0124", Color: 202}, // 󰄤
	"copyright.txt":                        {Icon: "\uf0124", Color: 202}, // 󰄤
	"credits":                              {Icon: "\uf0260", Color: 149}, // 󰉠
	"credits.md":                           {Icon: "\uf0260", Color: 149}, // 󰉠
	"credits.rst":                          {Icon: "\uf0260", Color: 149}, // 󰉠
	"credits.txt":                          {Icon: "\uf0260", Color: 149}, // 󰉠
	"dependabot.yaml":                      {Icon: "\uf4be", Color: 69},   // 
	"dependabot.yml":                       {Icon: "\uf4be", Color: 69},   // 
	"docker-compose.alpha.yaml":            {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.alpha.yml":             {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.beta.yaml":             {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.beta.yml":              {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.ci.yaml":               {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.ci.yml":                {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.dev.yaml":              {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.dev.yml":               {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.development.yaml":      {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.development.yml":       {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.local.yaml":            {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.local.yml":             {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.override.yaml":         {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.override.yml":          {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.prod.yaml":             {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.prod.yml":              {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.production.yaml":       {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.production.yml":        {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.stage.yaml":            {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.stage.yml":             {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.staging.yaml":          {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.staging.yml":           {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.test.yaml":             {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.test.yml":              {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.testing.yaml":          {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.testing.yml":           {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.web.yaml":              {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.web.yml":               {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.worker.yaml":           {Icon: "\uf21f", Color: 32},   // 
	"docker-compose.worker.yml":            {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.alpha":                     {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.beta":                      {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.ci":                        {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.dev":                       {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.development":               {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.local":                     {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.prod":                      {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.production":                {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.stage":                     {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.staging":                   {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.test":                      {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.testing":                   {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.web":                       {Icon: "\uf21f", Color: 32},   // 
	"dockerfile.worker":                    {Icon: "\uf21f", Color: 32},   // 
	"ember-cli-builds.js":                  {Icon: "\uf0b30", Color: 202}, // 󰬰
	"eslint.config.cts":                    {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"eslint.config.json":                   {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"eslint.config.json5":                  {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"eslint.config.jsonc":                  {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"eslint.config.mts":                    {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"eslint.config.toml":                   {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"eslint.config.yaml":                   {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"eslint.config.yml":                    {Icon: "\uf0c7a", Color: 61},  // 󰱺
	"firebase.json":                        {Icon: "\uf0967", Color: 214}, // 󰥧
	"firestore.indexes.json":               {Icon: "\uf0967", Color: 214}, // 󰥧
	"firestore.rules":                      {Icon: "\uf0967", Color: 214}, // 󰥧
	"funding.yml":                          {Icon: "\u2665", Color: 169},  // ♥
	"gatsby-browser.js":                    {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-browser.tsx":                   {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-config.js":                     {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-config.mjs":                    {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-config.ts":                     {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-node.js":                       {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-node.mjs":                      {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-node.ts":                       {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-ssr.js":                        {Icon: "\uf0e43", Color: 5},   // 󰹃
	"gatsby-ssr.tsx":                       {Icon: "\uf0e43", Color: 5},   // 󰹃
	"git-history":                          {Icon: "\uf02a2", Color: 166}, // 󰊢
	"go.work.sum":                          {Icon: "\uf07d3", Color: 204}, // 󰟓
	"graphql.config.cjs":                   {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.cts":                   {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.js":                    {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.json":                  {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.json5":                 {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.jsonc":                 {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.mjs":                   {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.mts":                   {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.toml":                  {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.ts":                    {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.yaml":                  {Icon: "\uf0877", Color: 204}, // 󰡷
	"graphql.config.yml":                   {Icon: "\uf0877", Color: 204}, // 󰡷
	"gulpfile.cts":                         {Icon: "\ue610", Color: 167},  // 
	"gulpfile.mjs":                         {Icon: "\ue610", Color: 167},  // 
	"gulpfile.mts":                         {Icon: "\ue610", Color: 167},  // 
	"hardhat.config.js":                    {Icon: "\uf096f", Color: 220}, // 󰥯
	"hardhat.config.ts":                    {Icon: "\uf096f", Color: 220}, // 󰥯
	"husky.config.cjs":                     {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.cts":                     {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.js":                      {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.json":                    {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.json5":                   {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.jsonc":                   {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.mjs":                     {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.mts":                     {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.toml":                    {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.ts":                      {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.yaml":                    {Icon: "\uf03e9", Color: 109}, // 󰏩
	"husky.config.yml":                     {Icon: "\uf03e9", Color: 109}, // 󰏩
	"jenkinsfile":                          {Icon: "\uf2ec", Color: 223},  // 
	"jsconfig.json":                        {Icon: "\ue60c", Color: 220},  // 
	"jvm.config":                           {Icon: "\uf06d3", Color: 203}, // 󰛓
	"k8s.yaml":                             {Icon: "\uf10fe", Color: 69},  // 󱃾
	"k8s.yml":                              {Icon: "\uf10fe", Color: 69},  // 󱃾
	"karma-main.js":                        {Icon: "\ue622", Color: 73},   // 
	"karma-main.ts":                        {Icon: "\ue622", Color: 73},   // 
	"karma.conf.coffee":                    {Icon: "\ue622", Color: 73},   // 
	"karma.conf.js":                        {Icon: "\ue622", Color: 73},   // 
	"karma.conf.ts":                        {Icon: "\ue622", Color: 73},   // 
	"karma.config.js":                      {Icon: "\ue622", Color: 73},   // 
	"karma.config.ts":                      {Icon: "\ue622", Color: 73},   // 
	"kbuild":                               {Icon: "\ueba2", Color: 203},  // 
	"knip.config.js":                       {Icon: "\uf0c4", Color: 202},  // 
	"knip.config.ts":                       {Icon: "\uf0c4", Color: 202},  // 
	"knip.js":                              {Icon: "\uf0c4", Color: 202},  // 
	"knip.json":                            {Icon: "\uf0c4", Color: 202},  // 
	"knip.jsonc":                           {Icon: "\uf0c4", Color: 202},  // 
	"knip.ts":                              {Icon: "\uf0c4", Color: 202},  // 
	"kubernetes.yaml":                      {Icon: "\uf10fe", Color: 69},  // 󱃾
	"kubernetes.yml":                       {Icon: "\uf10fe", Color: 69},  // 󱃾
	"license-agpl":                         {Icon: "\uf0124", Color: 220}, // 󰄤
	"license-apache":                       {Icon: "\uf0124", Color: 220}, // 󰄤
	"license-bsd":                          {Icon: "\uf0124", Color: 220}, // 󰄤
	"license-gpl":                          {Icon: "\uf0124", Color: 220}, // 󰄤
	"license-lgpl":                         {Icon: "\uf0124", Color: 220}, // 󰄤
	"license-mit":                          {Icon: "\uf0124", Color: 220}, // 󰄤
	"license.md":                           {Icon: "\uf0124", Color: 220}, // 󰄤
	"license.rst":                          {Icon: "\uf0124", Color: 220}, // 󰄤
	"license.txt":                          {Icon: "\uf0124", Color: 220}, // 󰄤
	"lighthouserc.cjs":                     {Icon: "\uf09ff", Color: 202}, // 󰧿
	"lighthouserc.js":                      {Icon: "\uf09ff", Color: 202}, // 󰧿
	"lighthouserc.json":                    {Icon: "\uf09ff", Color: 202}, // 󰧿
	"lighthouserc.yaml":                    {Icon: "\uf09ff", Color: 202}, // 󰧿
	"lighthouserc.yml":                     {Icon: "\uf09ff", Color: 202}, // 󰧿
	"manifest.mf":                          {Icon: "\uf013", Color: 75},   // 
	"maven.config":                         {Icon: "\uf06d3", Color: 203}, // 󰛓
	"milestones.md":                        {Icon: "\uf503", Color: 36},   // 
	"milestones.txt":                       {Icon: "\uf503", Color: 36},   // 
	"mocha.opts":                           {Icon: "\ue61b", Color: 138},  // 
	"moon.yml":                             {Icon: "\uf0f62", Color: 97},  // 󰽢
	"nginx.conf":                           {Icon: "\ue776", Color: 71},   // 
	"now.json":                             {Icon: "\uf0536", Color: 188}, // 󰔶
	"nyc.config.js":                        {Icon: "\uf1827", Color: 221}, // 󱠧
	"panda.config.cjs":                     {Icon: "\uf03da", Color: 231}, // 󰏚
	"panda.config.js":                      {Icon: "\uf03da", Color: 231}, // 󰏚
	"panda.config.mjs":                     {Icon: "\uf03da", Color: 231}, // 󰏚
	"panda.config.mts":                     {Icon: "\uf03da", Color: 231}, // 󰏚
	"panda.config.ts":                      {Icon: "\uf03da", Color: 231}, // 󰏚
	"playwright-ct.config.js":              {Icon: "\ueeb6", Color: 71},   // 
	"playwright-ct.config.mjs":             {Icon: "\ueeb6", Color: 71},   // 
	"playwright-ct.config.ts":              {Icon: "\ueeb6", Color: 71},   // 
	"playwright.config.base.js":            {Icon: "\ueeb6", Color: 71},   // 
	"playwright.config.base.mjs":           {Icon: "\ueeb6", Color: 71},   // 
	"playwright.config.base.ts":            {Icon: "\ueeb6", Color: 71},   // 
	"playwright.config.js":                 {Icon: "\ueeb6", Color: 71},   // 
	"playwright.config.mjs":                {Icon: "\ueeb6", Color: 71},   // 
	"playwright.config.ts":                 {Icon: "\ueeb6", Color: 71},   // 
	"plopfile.cjs":                         {Icon: "\uf0e0a", Color: 37},  // 󰸊
	"plopfile.js":                          {Icon: "\uf0e0a", Color: 37},  // 󰸊
	"plopfile.mjs":                         {Icon: "\uf0e0a", Color: 37},  // 󰸊
	"plopfile.ts":                          {Icon: "\uf0e0a", Color: 37},  // 󰸊
	"prettier.config.cts":                  {Icon: "\ue6b4", Color: 167},  // 
	"prettier.config.json":                 {Icon: "\ue6b4", Color: 167},  // 
	"prettier.config.json5":                {Icon: "\ue6b4", Color: 167},  // 
	"prettier.config.jsonc":                {Icon: "\ue6b4", Color: 167},  // 
	"prettier.config.mts":                  {Icon: "\ue6b4", Color: 167},  // 
	"prettier.config.toml":                 {Icon: "\ue6b4", Color: 167},  // 
	"prettier.config.yaml":                 {Icon: "\ue6b4", Color: 167},  // 
	"prettier.config.yml":                  {Icon: "\ue6b4", Color: 167},  // 
	"prisma.yml":                           {Icon: "\ue684", Color: 37},   // 
	"procfile.windows":                     {Icon: "\ue607", Color: 61},   // 
	"readme.md":                            {Icon: "\uf05a", Color: 75},   // 
	"readme.rst":                           {Icon: "\uf05a", Color: 75},   // 
	"readme.txt":                           {Icon: "\uf05a", Color: 75},   // 
	"renovate-config.json":                 {Icon: "\uee72", Color: 214},  // 
	"renovate.json":                        {Icon: "\uee72", Color: 214},  // 
	"renovate.json5":                       {Icon: "\uee72", Color: 214},  // 
	"roadmap.md":                           {Icon: "\uf503", Color: 36},   // 
	"roadmap.txt":                          {Icon: "\uf503", Color: 36},   // 
	"rollup-config.js":                     {Icon: "\ue689", Color: 203},  // 
	"rollup-config.mjs":                    {Icon: "\ue689", Color: 203},  // 
	"rollup-config.ts":                     {Icon: "\ue689", Color: 203},  // 
	"rollup.config.base.js":                {Icon: "\ue689", Color: 203},  // 
	"rollup.config.base.mjs":               {Icon: "\ue689", Color: 203},  // 
	"rollup.config.base.ts":                {Icon: "\ue689", Color: 203},  // 
	"rollup.config.common.js":              {Icon: "\ue689", Color: 203},  // 
	"rollup.config.common.mjs":             {Icon: "\ue689", Color: 203},  // 
	"rollup.config.common.ts":              {Icon: "\ue689", Color: 203},  // 
	"rollup.config.dev.js":                 {Icon: "\ue689", Color: 203},  // 
	"rollup.config.dev.mjs":                {Icon: "\ue689", Color: 203},  // 
	"rollup.config.dev.ts":                 {Icon: "\ue689", Color: 203},  // 
	"rollup.config.js":                     {Icon: "\ue689", Color: 203},  // 
	"rollup.config.mjs":                    {Icon: "\ue689", Color: 203},  // 
	"rollup.config.prod.js":                {Icon: "\ue689", Color: 203},  // 
	"rollup.config.prod.mjs":               {Icon: "\ue689", Color: 203},  // 
	"rollup.config.prod.ts":                {Icon: "\ue689", Color: 203},  // 
	"rollup.config.prod.vendor.js":         {Icon: "\ue689", Color: 203},  // 
	"rollup.config.prod.vendor.mjs":        {Icon: "\ue689", Color: 203},  // 
	"rollup.config.prod.vendor.ts":         {Icon: "\ue689", Color: 203},  // 
	"rollup.config.ts":                     {Icon: "\ue689", Color: 203},  // 
	"routes.js":                            {Icon: "\uf046a", Color: 71},  // 󰑪
	"routes.jsx":                           {Icon: "\uf046a", Color: 71},  // 󰑪
	"routes.ts":                            {Icon: "\uf046a", Color: 71},  // 󰑪
	"routes.tsx":                           {Icon: "\uf046a", Color: 71},  // 󰑪
	"security":                             {Icon: "\uf023", Color: 221},  // 
	"security.md":                          {Icon: "\uf023", Color: 221},  // 
	"security.txt":                         {Icon: "\uf023", Color: 221},  // 
	"stryker.conf.cjs":                     {Icon: "\uf01a3", Color: 203}, // 󰆣
	"stryker.conf.js":                      {Icon: "\uf01a3", Color: 203}, // 󰆣
	"stryker.conf.json":                    {Icon: "\uf01a3", Color: 203}, // 󰆣
	"stryker.conf.mjs":                     {Icon: "\uf01a3", Color: 203}, // 󰆣
	"stylelint.config.cjs":                 {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.cts":                 {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.js":                  {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.json":                {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.json5":               {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.jsonc":               {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.mjs":                 {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.mts":                 {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.toml":                {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.ts":                  {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.yaml":                {Icon: "\ue695", Color: 188},  // 
	"stylelint.config.yml":                 {Icon: "\ue695", Color: 188},  // 
	"svelte.config.cjs":                    {Icon: "\ue697", Color: 202},  // 
	"svgr.config.cjs":                      {Icon: "\ued46", Color: 208},  // 
	"svgr.config.cts":                      {Icon: "\ued46", Color: 208},  // 
	"svgr.config.js":                       {Icon: "\ued46", Color: 208},  // 
	"svgr.config.json":                     {Icon: "\ued46", Color: 208},  // 
	"svgr.config.json5":                    {Icon: "\ued46", Color: 208},  // 
	"svgr.config.jsonc":                    {Icon: "\ued46", Color: 208},  // 
	"svgr.config.mjs":                      {Icon: "\ued46", Color: 208},  // 
	"svgr.config.mts":                      {Icon: "\ued46", Color: 208},  // 
	"svgr.config.toml":                     {Icon: "\ued46", Color: 208},  // 
	"svgr.config.ts":                       {Icon: "\ued46", Color: 208},  // 
	"svgr.config.yaml":                     {Icon: "\ued46", Color: 208},  // 
	"svgr.config.yml":                      {Icon: "\ued46", Color: 208},  // 
	"swagger.json":                         {Icon: "\uf0626", Color: 71},  // 󰘦
	"swagger.yaml":                         {Icon: "\uf0626", Color: 71},  // 󰘦
	"swagger.yml":                          {Icon: "\uf0626", Color: 71},  // 󰘦
	"syncpack.config.cjs":                  {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.cts":                  {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.js":                   {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.json":                 {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.json5":                {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.jsonc":                {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.mjs":                  {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.mts":                  {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.toml":                 {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.ts":                   {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.yaml":                 {Icon: "\uf46a", Color: 113},  // 
	"syncpack.config.yml":                  {Icon: "\uf46a", Color: 113},  // 
	"tailwind.config.cjs":                  {Icon: "\uf13ff", Color: 73},  // 󱏿
	"tailwind.config.cts":                  {Icon: "\uf13ff", Color: 73},  // 󱏿
	"tailwind.config.mts":                  {Icon: "\uf13ff", Color: 73},  // 󱏿
	"tailwind.js":                          {Icon: "\uf13ff", Color: 73},  // 󱏿
	"tailwind.ts":                          {Icon: "\uf13ff", Color: 73},  // 󱏿
	"taskfile.dist.yaml":                   {Icon: "\uf1b2", Color: 80},   // 
	"taskfile.dist.yml":                    {Icon: "\uf1b2", Color: 80},   // 
	"taskfile.yaml":                        {Icon: "\uf1b2", Color: 80},   // 
	"taskfile.yml":                         {Icon: "\uf1b2", Color: 80},   // 
	"timeline.md":                          {Icon: "\uf503", Color: 36},   // 
	"timeline.txt":                         {Icon: "\uf503", Color: 36},   // 
	"todo.md":                              {Icon: "\uf058", Color: 107},  // 
	"todos.md":                             {Icon: "\uf058", Color: 107},  // 
	"tsconfig.app.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.base.json":                   {Icon: "\ue628", Color: 32},   // 
	"tsconfig.build.json":                  {Icon: "\ue628", Color: 32},   // 
	"tsconfig.cjs.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.config.json":                 {Icon: "\ue628", Color: 32},   // 
	"tsconfig.doc.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.e2e.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.editor.json":                 {Icon: "\ue628", Color: 32},   // 
	"tsconfig.eslint.json":                 {Icon: "\ue628", Color: 32},   // 
	"tsconfig.esm.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.lib.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.lib.prod.json":               {Icon: "\ue628", Color: 32},   // 
	"tsconfig.main.json":                   {Icon: "\ue628", Color: 32},   // 
	"tsconfig.mjs.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.node.json":                   {Icon: "\ue628", Color: 32},   // 
	"tsconfig.paths.json":                  {Icon: "\ue628", Color: 32},   // 
	"tsconfig.renderer.json":               {Icon: "\ue628", Color: 32},   // 
	"tsconfig.server.json":                 {Icon: "\ue628", Color: 32},   // 
	"tsconfig.spec.json":                   {Icon: "\ue628", Color: 32},   // 
	"tsconfig.test.json":                   {Icon: "\ue628", Color: 32},   // 
	"tsconfig.vitest.json":                 {Icon: "\ue628", Color: 32},   // 
	"tsconfig.web.json":                    {Icon: "\ue628", Color: 32},   // 
	"tsconfig.webworker.json":              {Icon: "\ue628", Color: 32},   // 
	"tsconfig.worker.json":                 {Icon: "\ue628", Color: 32},   // 
	"v.mod":                                {Icon: "\ue6ac", Color: 38},   // 
	"vercel.json":                          {Icon: "\uf0536", Color: 188}, // 󰔶
	"vetur.config.js":                      {Icon: "\ued4a", Color: 72},   // 
	"vetur.config.ts":                      {Icon: "\ued4a", Color: 72},   // 
	"vite.config.cjs":                      {Icon: "\uf0241", Color: 214}, // 󰉁
	"vite.config.cts":                      {Icon: "\uf0241", Color: 214}, // 󰉁
	"vite.config.js":                       {Icon: "\uf0241", Color: 214}, // 󰉁
	"vite.config.mjs":                      {Icon: "\uf0241", Color: 214}, // 󰉁
	"vite.config.mts":                      {Icon: "\uf0241", Color: 214}, // 󰉁
	"vite.config.ts":                       {Icon: "\uf0241", Color: 214}, // 󰉁
	"volar.config.js":                      {Icon: "\ued4a", Color: 72},   // 
	"vpkg.json":                            {Icon: "\ue6ac", Color: 38},   // 
	"vue.config.js":                        {Icon: "\ued4a", Color: 72},   // 
	"vue.config.ts":                        {Icon: "\ued4a", Color: 72},   // 
	"webpack.base.cjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.base.cts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.base.js":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.base.mjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.base.mts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.base.ts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.cjs":                          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.client.cjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.client.cts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.client.js":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.client.mjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.client.mts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.client.ts":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.common.cjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.common.cts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.common.js":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.common.mjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.common.mts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.common.ts":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.babel.cjs":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.babel.cts":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.babel.js":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.babel.mjs":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.babel.mts":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.babel.ts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.babel.cjs":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.babel.cts":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.babel.js":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.babel.mjs":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.babel.mts":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.babel.ts":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.cjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.cts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.js":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.mjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.mts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.base.ts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.cjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.client.cjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.client.cts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.client.js":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.client.mjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.client.mts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.client.ts":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.coffee":                {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.babel.cjs":      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.babel.cts":      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.babel.js":       {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.babel.mjs":      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.babel.mts":      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.babel.ts":       {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.cjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.cts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.js":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.mjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.mts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.common.ts":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.cts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.babel.cjs":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.babel.cts":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.babel.js":          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.babel.mjs":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.babel.mts":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.babel.ts":          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.cjs":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.cts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.js":                {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.mjs":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.mts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.dev.ts":                {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.js":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.main.cjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.main.cts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.main.js":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.main.mjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.main.mts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.main.ts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.mjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.mts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.babel.cjs":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.babel.cts":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.babel.js":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.babel.mjs":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.babel.mts":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.babel.ts":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.cjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.cts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.js":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.mjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.mts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.prod.ts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.babel.cjs":  {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.babel.cts":  {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.babel.js":   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.babel.mjs":  {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.babel.mts":  {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.babel.ts":   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.cjs":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.cts":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.js":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.mjs":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.mts":        {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.production.ts":         {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.renderer.cjs":          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.renderer.cts":          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.renderer.js":           {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.renderer.mjs":          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.renderer.mts":          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.renderer.ts":           {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.server.cjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.server.cts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.server.js":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.server.mjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.server.mts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.server.ts":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.babel.cjs":     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.babel.cts":     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.babel.js":      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.babel.mjs":     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.babel.mts":     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.babel.ts":      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.cjs":           {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.cts":           {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.js":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.mjs":           {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.mts":           {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.staging.ts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.test.cjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.test.cts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.test.js":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.test.mjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.test.mts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.test.ts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.ts":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.cjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.cts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.js":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.mjs":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.mts":            {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.production.cjs": {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.production.cts": {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.production.js":  {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.production.mjs": {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.production.mts": {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.production.ts":  {Icon: "\ue6a3", Color: 117},  // 
	"webpack.config.vendor.ts":             {Icon: "\ue6a3", Color: 117},  // 
	"webpack.cts":                          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dev.cjs":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dev.cts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dev.js":                       {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dev.mjs":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dev.mts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dev.ts":                       {Icon: "\ue6a3", Color: 117},  // 
	"webpack.development.cjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.development.cts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.development.js":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.development.mjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.development.mts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.development.ts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dist.cjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dist.cts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dist.js":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dist.mjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dist.mts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.dist.ts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.js":                           {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mix.cjs":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mix.cts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mix.js":                       {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mix.mjs":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mix.mts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mix.ts":                       {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mjs":                          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.mts":                          {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.cjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.config.cjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.config.cts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.config.js":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.config.mjs":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.config.mts":              {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.config.ts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.cts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.js":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.mjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.mts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.prod.ts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.production.cjs":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.production.cts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.production.js":                {Icon: "\ue6a3", Color: 117},  // 
	"webpack.production.mjs":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.production.mts":               {Icon: "\ue6a3", Color: 117},  // 
	"webpack.production.ts":                {Icon: "\ue6a3", Color: 117},  // 
	"webpack.server.cjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.server.cts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.server.js":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.server.mjs":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.server.mts":                   {Icon: "\ue6a3", Color: 117},  // 
	"webpack.server.ts":                    {Icon: "\ue6a3", Color: 117},  // 
	"webpack.test.cjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.test.cts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.test.js":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.test.mjs":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.test.mts":                     {Icon: "\ue6a3", Color: 117},  // 
	"webpack.test.ts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpack.ts":                           {Icon: "\ue6a3", Color: 117},  // 
	"webpackfile.cjs":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpackfile.cts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpackfile.js":                       {Icon: "\ue6a3", Color: 117},  // 
	"webpackfile.mjs":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpackfile.mts":                      {Icon: "\ue6a3", Color: 117},  // 
	"webpackfile.ts":                       {Icon: "\ue6a3", Color: 117},  // 
	"windi.config.cjs":                     {Icon: "\uef16", Color: 75},   // 
	"windi.config.cts":                     {Icon: "\uef16", Color: 75},   // 
	"windi.config.js":                      {Icon: "\uef16", Color: 75},   // 
	"windi.config.json":                    {Icon: "\uef16", Color: 75},   // 
	"windi.config.ts":                      {Icon: "\uef16", Color: 75},   // 
	"yarn-error.log":                       {Icon: "\ue6a7", Color: 203},  // 
}

var extIconMap = map[string]IconProperties{
	".a51":                  {Icon: "\uf0628", Color: 203}, // 󰘨
	".abc":                  {Icon: "\uf0f70", Color: 202}, // 󰽰
	".accda":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".accdb":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".accdc":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".accde":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".accdp":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".accdr":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".accdt":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".accdu":                {Icon: "\uf138e", Color: 125}, // 󱎎
	".ac":                   {Icon: "\uea8c", Color: 39},   // 
	".ada":                  {Icon: "\uf15c6", Color: 31},  // 󱗆
	".adb":                  {Icon: "\uf15c6", Color: 31},  // 󱗆
	".ade":                  {Icon: "\uf138e", Color: 125}, // 󱎎
	".adp":                  {Icon: "\uf138e", Color: 125}, // 󱎎
	".ads":                  {Icon: "\uf15c6", Color: 31},  // 󱗆
	".aea":                  {Icon: "\uf0628", Color: 203}, // 󰘨
	".afphoto":              {Icon: "\uf021f", Color: 37},  // 󰈟
	".agc":                  {Icon: "\uf0628", Color: 203}, // 󰘨
	".age":                  {Icon: "\ueafa", Color: 221},  // 
	".ags":                  {Icon: "\uf0628", Color: 203}, // 󰘨
	".ahk":                  {Icon: "\uf0fd", Color: 71},   // 
	".ali":                  {Icon: "\uf15c6", Color: 31},  // 󱗆
	".ami":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".amx":                  {Icon: "\uf0859", Color: 202}, // 󰡙
	".apx":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".argus":                {Icon: "\uf0628", Color: 203}, // 󰘨
	".ase":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".aseprite":             {Icon: "\uf021f", Color: 37},  // 󰈟
	".asm":                  {Icon: "\uf0628", Color: 203}, // 󰘨
	".asp":                  {Icon: "\uf13b", Color: 166},  // 
	".bf":                   {Icon: "\uf09d1", Color: 204}, // 󰧑
	".b":                    {Icon: "\uf09d1", Color: 204}, // 󰧑
	".binsource":            {Icon: "\uf0628", Color: 203}, // 󰘨
	".bmap":                 {Icon: "\ue659", Color: 203},  // 
	".bpg":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".br":                   {Icon: "\uf05c4", Color: 142}, // 󰗄
	".brk":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".brotli":               {Icon: "\uf05c4", Color: 142}, // 󰗄
	".bzip2":                {Icon: "\uf05c4", Color: 142}, // 󰗄
	".cake":                 {Icon: "\uf1fd", Color: 203},  // 
	".cer":                  {Icon: "\uf0124", Color: 202}, // 󰄤
	".cert":                 {Icon: "\uf0124", Color: 202}, // 󰄤
	".cfc":                  {Icon: "\ue645", Color: 204},  // 
	".cfm":                  {Icon: "\ue645", Color: 204},  // 
	".cfml":                 {Icon: "\ue645", Color: 204},  // 
	".cjs.map":              {Icon: "\ue60c", Color: 220},  // 
	".cl":                   {Icon: "\ue6b0", Color: 203},  // 
	".clip":                 {Icon: "\uf021f", Color: 37},  // 󰈟
	".cmx":                  {Icon: "\ue67a", Color: 208},  // 
	".code-profile":         {Icon: "\uf0a1e", Color: 33},  // 󰨞
	".code-search":          {Icon: "\uf0c7c", Color: 75},  // 󰱼
	".code-snippets":        {Icon: "\uf0a1e", Color: 33},  // 󰨞
	".code-workplace":       {Icon: "\uf0a1e", Color: 33},  // 󰨞
	".code-workspace":       {Icon: "\uf0a1e", Color: 33},  // 󰨞
	".command":              {Icon: "\uf0633", Color: 109}, // 󰘳
	".component.js":         {Icon: "\ued4b", Color: 32},   // 
	".component.ts":         {Icon: "\ued4b", Color: 32},   // 
	".cpt":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".crt":                  {Icon: "\uf0124", Color: 202}, // 󰄤
	".crx":                  {Icon: "\uf268", Color: 75},   // 
	".csharp":               {Icon: "\uf031b", Color: 32},  // 󰌛
	".css.map":              {Icon: "\uf13c", Color: 75},   // 
	".cur":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".cy.js":                {Icon: "\uf499", Color: 220},  // 
	".cy.jsx":               {Icon: "\uf499", Color: 220},  // 
	".cy.tsx":               {Icon: "\uf499", Color: 32},   // 
	".dat":                  {Icon: "\uf12a7", Color: 36},  // 󱊧
	".db3":                  {Icon: "\uf1c0", Color: 220},  // 
	".dblite3":              {Icon: "\uf1c0", Color: 220},  // 
	".dblite":               {Icon: "\uf1c0", Color: 220},  // 
	".d.cts":                {Icon: "\ue628", Color: 32},   // 
	".dds":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".debugsymbols":         {Icon: "\uf1c0", Color: 220},  // 
	".dex":                  {Icon: "\ue70e", Color: 113},  // 
	".dhallb":               {Icon: "\uf0d13", Color: 103}, // 󰴓
	".dhall":                {Icon: "\uf0d13", Color: 103}, // 󰴓
	".directive.js":         {Icon: "\ued4b", Color: 133},  // 
	".directive.ts":         {Icon: "\ued4b", Color: 133},  // 
	".django-html":          {Icon: "\ue71d", Color: 71},   // 
	".django-txt":           {Icon: "\ue71d", Color: 71},   // 
	".djt":                  {Icon: "\ue71d", Color: 71},   // 
	".dlc":                  {Icon: "\uf013", Color: 75},   // 
	".dmg":                  {Icon: "\uede9", Color: 250},  // 
	".dmn":                  {Icon: "\uf022e", Color: 113}, // 󰈮
	".d.mts":                {Icon: "\ue628", Color: 32},   // 
	".dng":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".drone.yml":            {Icon: "\uf041d", Color: 188}, // 󰐝
	".dsc":                  {Icon: "\ue651", Color: 221},  // 
	".dtd":                  {Icon: "\uf022e", Color: 113}, // 󰈮
	".dtx":                  {Icon: "\ue69b", Color: 75},   // 
	".e2e-spec.cjs":         {Icon: "\uf499", Color: 220},  // 
	".e2e-spec.js":          {Icon: "\uf499", Color: 220},  // 
	".e2e-spec.mjs":         {Icon: "\uf499", Color: 220},  // 
	".ecr":                  {Icon: "\ue62f", Color: 188},  // 
	".edge":                 {Icon: "\uf486", Color: 202},  // 
	".eps":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".esx":                  {Icon: "\uf031e", Color: 220}, // 󰌞
	".exp":                  {Icon: "\uf018d", Color: 203}, // 󰆍
	".exrc":                 {Icon: "\ue62b", Color: 71},   // 
	".exr":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".f03":                  {Icon: "\uf121a", Color: 203}, // 󱈚
	".f08":                  {Icon: "\uf121a", Color: 203}, // 󱈚
	".f77":                  {Icon: "\uf121a", Color: 203}, // 󱈚
	".f95":                  {Icon: "\uf121a", Color: 203}, // 󱈚
	".fast":                 {Icon: "\ue6b0", Color: 203},  // 
	".fen":                  {Icon: "\uf0857", Color: 188}, // 󰡗
	".f":                    {Icon: "\uf121a", Color: 203}, // 󱈚
	".fig":                  {Icon: "\uef47", Color: 202},  // 
	".fnt":                  {Icon: "\ue659", Color: 203},  // 
	".fonts":                {Icon: "\ue659", Color: 203},  // 
	".fpx":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".freezed.dart":         {Icon: "\ue64c", Color: 109},  // 
	".fsproj":               {Icon: "\ue7a7", Color: 74},   // 
	".g4":                   {Icon: "\uf109a", Color: 203}, // 󱂚
	".gbr":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".g.dart":               {Icon: "\ue64c", Color: 109},  // 
	".gdextension":          {Icon: "\ue65f", Color: 71},   // 
	".gdnlib":               {Icon: "\ue65f", Color: 71},   // 
	".gdns":                 {Icon: "\ue65f", Color: 71},   // 
	".gdshader":             {Icon: "\ue65f", Color: 71},   // 
	".gdshaderinc":          {Icon: "\ue65f", Color: 71},   // 
	".gemini":               {Icon: "\uf059f", Color: 114}, // 󰖟
	".gifv":                 {Icon: "\uf0381", Color: 208}, // 󰎁
	".gitlab-ci.yml":        {Icon: "\uf296", Color: 167},  // 
	".gmi":                  {Icon: "\uf059f", Color: 114}, // 󰖟
	".gpg":                  {Icon: "\uf0306", Color: 36},  // 󰌆
	".guard.js":             {Icon: "\ued4b", Color: 71},   // 
	".guard.ts":             {Icon: "\ued4b", Color: 71},   // 
	".gvimrc":               {Icon: "\ue62b", Color: 71},   // 
	".gzip":                 {Icon: "\uf05c4", Color: 142}, // 󰗄
	".hdd":                  {Icon: "\uede9", Color: 250},  // 
	".heic":                 {Icon: "\uf021f", Color: 37},  // 󰈟
	".heif":                 {Icon: "\uf021f", Color: 37},  // 󰈟
	".h++":                  {Icon: "\uf0fd", Color: 32},   // 
	".hp":                   {Icon: "\uf0fd", Color: 32},   // 
	".html_vm":              {Icon: "\uf13b", Color: 166},  // 
	".http":                 {Icon: "\uf059f", Color: 167}, // 󰖟
	".ibc":                  {Icon: "\uf06d3", Color: 203}, // 󰛓
	".iced":                 {Icon: "\ue61b", Color: 239},  // 
	".icns":                 {Icon: "\uf021f", Color: 37},  // 󰈟
	".idr":                  {Icon: "\uf06d3", Color: 203}, // 󰛓
	".i":                    {Icon: "\ue649", Color: 32},   // 
	".ii":                   {Icon: "\ue646", Color: 32},   // 
	".ilk":                  {Icon: "\uf107c", Color: 75},  // 󱁼
	".inc":                  {Icon: "\uf0628", Color: 203}, // 󰘨
	".inky.php":             {Icon: "\uf2f7", Color: 203},  // 
	".inl":                  {Icon: "\uf0fd", Color: 32},   // 
	".ipa":                  {Icon: "\uf302", Color: 103},  // 
	".j2":                   {Icon: "\ue66f", Color: 250},  // 
	".jade":                 {Icon: "\ue686", Color: 223},  // 
	".jb2":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".jbig2":                {Icon: "\uf021f", Color: 37},  // 󰈟
	".jenkins":              {Icon: "\uf2ec", Color: 223},  // 
	".jinja2":               {Icon: "\ue66f", Color: 250},  // 
	".jinja-html":           {Icon: "\ue66f", Color: 250},  // 
	".jinja":                {Icon: "\ue66f", Color: 250},  // 
	".jng":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".jrxml":                {Icon: "\uf022e", Color: 113}, // 󰈮
	".js.map":               {Icon: "\ue60c", Color: 220},  // 
	".jsonl":                {Icon: "\ue60b", Color: 214},  // 
	".jsp":                  {Icon: "\uf0f4", Color: 203},  // 
	".js.snap":              {Icon: "\uf499", Color: 220},  // 
	".jsx.snap":             {Icon: "\uf499", Color: 220},  // 
	".jxr":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".key":                  {Icon: "\uf0306", Color: 36},  // 󰌆
	".laccdb":               {Icon: "\uf138e", Color: 125}, // 󱎎
	".lang":                 {Icon: "\uf05ca", Color: 104}, // 󰗊
	".ldb":                  {Icon: "\uf138e", Color: 125}, // 󱎎
	".lisp":                 {Icon: "\ue6b0", Color: 203},  // 
	".lol":                  {Icon: "\uf011b", Color: 203}, // 󰄛
	".ls":                   {Icon: "\ue671", Color: 67},   // 
	".lsp":                  {Icon: "\ue6b0", Color: 203},  // 
	".ltx":                  {Icon: "\ue69b", Color: 75},   // 
	".lucee":                {Icon: "\ue645", Color: 204},  // 
	".ly":                   {Icon: "\uf001", Color: 71},   // 
	".m2v":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".mam":                  {Icon: "\uf138e", Color: 125}, // 󱎎
	".manifest":             {Icon: "\uf022e", Color: 113}, // 󰈮
	".maq":                  {Icon: "\uf138e", Color: 125}, // 󱎎
	".mcaddon":              {Icon: "\uf0373", Color: 71},  // 󰍳
	".mca":                  {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcfunction":           {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcgame":               {Icon: "\uf0373", Color: 71},  // 󰍳
	".mclevel":              {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcmeta":               {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcpack":               {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcproject":            {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcr":                  {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcstructure":          {Icon: "\uf0373", Color: 71},  // 󰍳
	".mctemplate":           {Icon: "\uf0373", Color: 71},  // 󰍳
	".mcworld":              {Icon: "\uf0373", Color: 71},  // 󰍳
	".mdb":                  {Icon: "\uf138e", Color: 125}, // 󱎎
	".mdp":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".mdw":                  {Icon: "\uf138e", Color: 125}, // 󱎎
	".merlin":               {Icon: "\ue673", Color: 75},   // 
	".mesh":                 {Icon: "\uea8c", Color: 39},   // 
	".mi":                   {Icon: "\ue649", Color: 32},   // 
	".mii":                  {Icon: "\ue646", Color: 32},   // 
	".mine":                 {Icon: "\uf0373", Color: 71},  // 󰍳
	".mitigus":              {Icon: "\uf0628", Color: 203}, // 󰘨
	".mjs.map":              {Icon: "\ue60c", Color: 220},  // 
	".module.js":            {Icon: "\ued4b", Color: 167},  // 
	".module.ts":            {Icon: "\ued4b", Color: 167},  // 
	".moon":                 {Icon: "\uf186", Color: 214},  // 
	".mp2":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".mpeg":                 {Icon: "\uf0381", Color: 208}, // 󰎁
	".mpe":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".mpg":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".mpv":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".mqo":                  {Icon: "\uea8c", Color: 39},   // 
	".mrf":                  {Icon: "\ue659", Color: 203},  // 
	".ms":                   {Icon: "\uf0628", Color: 203}, // 󰘨
	".mus":                  {Icon: "\uf0373", Color: 71},  // 󰍳
	".mxml":                 {Icon: "\uf022e", Color: 214}, // 󰈮
	".nasm":                 {Icon: "\uf0628", Color: 203}, // 󰘨
	".ndjson":               {Icon: "\ue60b", Color: 214},  // 
	".nginxconf":            {Icon: "\ue776", Color: 71},   // 
	".nginxconfig":          {Icon: "\ue776", Color: 71},   // 
	".nginx":                {Icon: "\ue776", Color: 71},   // 
	".ng-template":          {Icon: "\ued4b", Color: 167},  // 
	".nimble":               {Icon: "\ue677", Color: 220},  // 
	".njk":                  {Icon: "\ue679", Color: 65},   // 
	".ntf":                  {Icon: "\ue659", Color: 203},  // 
	".nunjucks":             {Icon: "\ue679", Color: 65},   // 
	".odttf":                {Icon: "\ue659", Color: 203},  // 
	".opam":                 {Icon: "\ue67a", Color: 208},  // 
	".option":               {Icon: "\uf013", Color: 75},   // 
	".ora":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".pas":                  {Icon: "\uf03e3", Color: 32},  // 󰏣
	".passwd":               {Icon: "\uf0306", Color: 36},  // 󰌆
	".pbm":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".pdb":                  {Icon: "\uf1c0", Color: 220},  // 
	".pdn":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".pem":                  {Icon: "\uf0306", Color: 36},  // 󰌆
	".pgf":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".pgm":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".pgn":                  {Icon: "\uf0857", Color: 188}, // 󰡗
	".pgsql":                {Icon: "\uf1c0", Color: 220},  // 
	".pic":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".p":                    {Icon: "\uf03d2", Color: 203}, // 󰏒
	".pine":                 {Icon: "\uf0405", Color: 71},  // 󰐅
	".pipe.js":              {Icon: "\ued4b", Color: 203},  // 
	".pipeline":             {Icon: "\ue680", Color: 208},  // 
	".pipe.ts":              {Icon: "\ued4b", Color: 203},  // 
	".pkb":                  {Icon: "\uf1c0", Color: 220},  // 
	".pkl":                  {Icon: "\uf013", Color: 71},   // 
	".pks":                  {Icon: "\uf1c0", Color: 220},  // 
	".plist":                {Icon: "\uf022e", Color: 113}, // 󰈮
	".plpgsql":              {Icon: "\uf1c0", Color: 220},  // 
	".pmd":                  {Icon: "\uea8c", Color: 39},   // 
	".pmx":                  {Icon: "\uea8c", Color: 39},   // 
	".pnm":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".postgres":             {Icon: "\uf1c0", Color: 220},  // 
	".potm":                 {Icon: "\uf0227", Color: 166}, // 󰈧
	".potx":                 {Icon: "\uf0227", Color: 166}, // 󰈧
	".ppa":                  {Icon: "\uf0227", Color: 166}, // 󰈧
	".ppam":                 {Icon: "\uf0227", Color: 166}, // 󰈧
	".ppm":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".pps":                  {Icon: "\uf0227", Color: 166}, // 󰈧
	".ppsm":                 {Icon: "\uf0227", Color: 166}, // 󰈧
	".ppsx":                 {Icon: "\uf0227", Color: 166}, // 󰈧
	".pptm":                 {Icon: "\uf0227", Color: 166}, // 󰈧
	".prefs":                {Icon: "\uf013", Color: 75},   // 
	".project":              {Icon: "\uf022e", Color: 113}, // 󰈮
	".prop":                 {Icon: "\uf013", Color: 75},   // 
	".props":                {Icon: "\uf013", Color: 75},   // 
	".ps1xml":               {Icon: "\uf0a0a", Color: 39},  // 󰨊
	".psc1":                 {Icon: "\uf0a0a", Color: 39},  // 󰨊
	".psql":                 {Icon: "\uf1c0", Color: 220},  // 
	".pssc":                 {Icon: "\uf0a0a", Color: 39},  // 󰨊
	".psv":                  {Icon: "\uf021b", Color: 113}, // 󰈛
	".pug":                  {Icon: "\ue686", Color: 223},  // 
	".puppet":               {Icon: "\ue631", Color: 214},  // 
	".pure":                 {Icon: "\ue630", Color: 75},   // 
	".purs":                 {Icon: "\ue630", Color: 75},   // 
	".pwn":                  {Icon: "\uf0859", Color: 202}, // 󰡙
	".qcow2":                {Icon: "\uede9", Color: 250},  // 
	".qcow":                 {Icon: "\uede9", Color: 250},  // 
	".qed":                  {Icon: "\uede9", Color: 250},  // 
	".qt":                   {Icon: "\uf0381", Color: 208}, // 󰎁
	".raku":                 {Icon: "\ue769", Color: 104},  // 
	".raml":                 {Icon: "\uf0626", Color: 75},  // 󰘦
	".raw":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".rbs":                  {Icon: "\uf0d2d", Color: 203}, // 󰴭
	".reason":               {Icon: "\ue687", Color: 203},  // 
	".reason_lisp":          {Icon: "\ue687", Color: 203},  // 
	".reb":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".resolver.js":          {Icon: "\ued4b", Color: 218},  // 
	".resolver.ts":          {Icon: "\ued4b", Color: 218},  // 
	".rest":                 {Icon: "\uf059f", Color: 167}, // 󰖟
	".resx":                 {Icon: "\uf022e", Color: 113}, // 󰈮
	".rm":                   {Icon: "\uf0381", Color: 208}, // 󰎁
	".rmvb":                 {Icon: "\uf0381", Color: 208}, // 󰎁
	".robot":                {Icon: "\uf167a", Color: 37},  // 󱙺
	".ron":                  {Icon: "\ue68b", Color: 203},  // 
	".routing.js":           {Icon: "\uf046a", Color: 71},  // 󰑪
	".routing.jsx":          {Icon: "\uf046a", Color: 71},  // 󰑪
	".routing.ts":           {Icon: "\uf046a", Color: 71},  // 󰑪
	".routing.tsx":          {Icon: "\uf046a", Color: 71},  // 󰑪
	".rst":                  {Icon: "\ueb1d", Color: 75},   // 
	".ruleset":              {Icon: "\uf0610", Color: 133}, // 󰘐
	".sai":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".service.js":           {Icon: "\ued4b", Color: 220},  // 
	".service.ts":           {Icon: "\ued4b", Color: 220},  // 
	".settings":             {Icon: "\uf013", Color: 75},   // 
	".s":                    {Icon: "\uf0628", Color: 203}, // 󰘨
	".sketch":               {Icon: "\uf01c8", Color: 214}, // 󰇈
	".sln.dotsettings":      {Icon: "\uf013", Color: 75},   // 
	".sln.dotsettings.user": {Icon: "\uf013", Color: 75},   // 
	".slnx":                 {Icon: "\uf0610", Color: 133}, // 󰘐
	".smali":                {Icon: "\ue70e", Color: 113},  // 
	".spec.cjs":             {Icon: "\uf499", Color: 220},  // 
	".spec-d.tsx":           {Icon: "\uf499", Color: 32},   // 
	".spec.mjs":             {Icon: "\uf499", Color: 220},  // 
	".ss":                   {Icon: "\uf0627", Color: 203}, // 󰘧
	".sublime-project":      {Icon: "\ue696", Color: 215},  // 
	".sublime-workspace":    {Icon: "\ue696", Color: 215},  // 
	".sui":                  {Icon: "\ue659", Color: 203},  // 
	".suit":                 {Icon: "\ue659", Color: 203},  // 
	".svx":                  {Icon: "\ueb1d", Color: 202},  // 
	".tcc":                  {Icon: "\uf0fd", Color: 32},   // 
	".tcsh":                 {Icon: "\uf018d", Color: 203}, // 󰆍
	".template":             {Icon: "\uf0613", Color: 109}, // 󰘓
	".test.cjs":             {Icon: "\uf499", Color: 220},  // 
	".test-d.tsx":           {Icon: "\uf499", Color: 32},   // 
	".test.mjs":             {Icon: "\uf499", Color: 220},  // 
	".tfbackend":            {Icon: "\ue69a", Color: 61},   // 
	".tf.json":              {Icon: "\ue69a", Color: 61},   // 
	".tfstate":              {Icon: "\ue69a", Color: 61},   // 
	".tga":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".tif":                  {Icon: "\uf021f", Color: 37},  // 󰈟
	".tmLanguage":           {Icon: "\uf022e", Color: 113}, // 󰈮
	".todo":                 {Icon: "\uf058", Color: 107},  // 
	".tpl":                  {Icon: "\uf400", Color: 220},  // 
	".tree":                 {Icon: "\uf0645", Color: 107}, // 󰙅
	".tsbuildinfo":          {Icon: "\ue60b", Color: 214},  // 
	".tsx.snap":             {Icon: "\uf499", Color: 32},   // 
	".ttc":                  {Icon: "\ue659", Color: 203},  // 
	".unity":                {Icon: "\uf06af", Color: 32},  // 󰚯
	".uproject":             {Icon: "\uf09b1", Color: 231}, // 󰦱
	".url":                  {Icon: "\uf0339", Color: 75},  // 󰌹
	".vac":                  {Icon: "\uea8c", Color: 39},   // 
	".vbhtml":               {Icon: "\uf486", Color: 75},   // 
	".vb":                   {Icon: "\uf0610", Color: 133}, // 󰘐
	".vbox":                 {Icon: "\uf0322", Color: 38},  // 󰌢
	".vbox-prev":            {Icon: "\uf0322", Color: 38},  // 󰌢
	".vbs":                  {Icon: "\uf0610", Color: 133}, // 󰘐
	".vcxitems.filters":     {Icon: "\uf0610", Color: 133}, // 󰘐
	".vcxitems":             {Icon: "\uf0610", Color: 133}, // 󰘐
	".vcxproj.filters":      {Icon: "\uf0610", Color: 133}, // 󰘐
	".vcxproj":              {Icon: "\uf0610", Color: 133}, // 󰘐
	".vdi":                  {Icon: "\uf0322", Color: 38},  // 󰌢
	".vdp":                  {Icon: "\uea8c", Color: 39},   // 
	".viminfo":              {Icon: "\ue62b", Color: 71},   // 
	".vimrc":                {Icon: "\ue62b", Color: 71},   // 
	".vmdk":                 {Icon: "\uede9", Color: 250},  // 
	".vob":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".vox":                  {Icon: "\uea8c", Color: 39},   // 
	".vscodeignore":         {Icon: "\uf0a1e", Color: 33},  // 󰨞
	".vsixmanifest":         {Icon: "\uf0a1e", Color: 33},  // 󰨞
	".wat":                  {Icon: "\ue6a1", Color: 99},   // 
	".windi":                {Icon: "\uef16", Color: 75},   // 
	".wmv":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".xlsm":                 {Icon: "\uf021b", Color: 113}, // 󰈛
	".xml.dist":             {Icon: "\uf022e", Color: 113}, // 󰈮
	".xml.dist.sample":      {Icon: "\uf022e", Color: 113}, // 󰈮
	".xquery":               {Icon: "\uf022e", Color: 113}, // 󰈮
	".xsd":                  {Icon: "\uf022e", Color: 113}, // 󰈮
	".xsl":                  {Icon: "\uf022e", Color: 113}, // 󰈮
	".xslt":                 {Icon: "\uf022e", Color: 113}, // 󰈮
	".yaml.dist":            {Icon: "\uf0219", Color: 203}, // 󰈙
	".YAML-tmLanguage":      {Icon: "\uf0219", Color: 203}, // 󰈙
	".yang":                 {Icon: "\ueee9", Color: 75},   // 
	".yml.dist":             {Icon: "\uf0219", Color: 203}, // 󰈙
	".yuv":                  {Icon: "\uf0381", Color: 208}, // 󰎁
	".zon":                  {Icon: "\ue6a9", Color: 214},  // 
}
